[package]
name = "sandblaster-corpusgen"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sandblaster-core = { path = "../core" }
sandblaster-disasm = { path = "../disasm" }
sandblaster-injector = { path = "../injector" }
sandblaster-search = { path = "../search" }

[lib]
name = "sandblaster_corpusgen"
path = "src/lib.rs"
